# valid options
# groupname:
#   hosts:
#     - host1
#     - host2
#   ssh: "/path/to/ssh"
#   ssh_opts: "--valid ssh_options"
#   env: "SOME_ENV=variables"
#   command: "echo 'a default command is suggested, I use hostname'"
#   threaded: true|false
#   max_threads: Fixnum
#
#
---
default:
  hosts:
    - localhost
  command: hostname
rubyops:
  hosts:
    - www.rubyops.net
  command: hostname

