# this file contains all valid options
---
#max_threads: 5
#threaded: true
#dry_run: true
#username: jmervine
hosts:
  - localhost
  - www.rubyops.net
command: hostname
#ssh: "/usr/bin/ssh"
#ssh_opts: "-i ~/.ssh/id_rsa"
#env: "FOO=bar"

