---
default:
  max_threads: 10
  dry_run: true
  username: jmervine
  hosts:
    - localhost
  commands: 
    - hostname
  ssh_opts: 
    forward_agent: true
    keys: 
      - "~/.ssh/id_rsa"
  env: "FOO=bar"

